"""empty message

Revision ID: eb131fdc1c56
Revises: fcca9b0850bc
Create Date: 2019-08-18 21:15:35.336558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb131fdc1c56'
down_revision = 'fcca9b0850bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'updated_at')
    # ### end Alembic commands ###
